services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: quotes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_DSN=postgres://user:pass@db:5432/quotes?sslmode=disable
    volumes:
      - ./init.sql:/app/init.sql:ro
      - ./supported_currency.json:/app/supported_currency.json:ro